INSERT INTO tb_category (name) VALUES ('Livros');
INSERT INTO tb_category (name) VALUES ('Eletrônicos');
INSERT INTO tb_category (name) VALUES ('Computadores');

INSERT INTO tb_product (name) VALUES ('The Lord of the Rings');
INSERT INTO tb_product (name) VALUES ('Smart TV');
INSERT INTO tb_product (name) VALUES ('Macbook Pro');
INSERT INTO tb_product (name) VALUES ('PC Gamer');
INSERT INTO tb_product (name) VALUES ('Rails for Dummie5-big.jpg');
INSERT INTO tb_product (name) VALUES ('PC Gamer Ex');
INSERT INTO tb_product (name) VALUES ('PC Gamer X');
INSERT INTO tb_product (name) VALUES ('PC Gamer Alfa');
INSERT INTO tb_product (name) VALUES ('PC Gamer Tera');
INSERT INTO tb_product (name) VALUES ('PC Gamer Y');
INSERT INTO tb_product (name) VALUES ('PC Gamer Nitro');
INSERT INTO tb_product (name) VALUES ('PC Gamer Card');
INSERT INTO tb_product (name) VALUES ('PC Gamer Plus');
INSERT INTO tb_product (name) VALUES ('PC Gamer Hera');
INSERT INTO tb_product (name) VALUES ('PC Gamer Weed');
INSERT INTO tb_product (name) VALUES ('PC Gamer Max');
INSERT INTO tb_product (name) VALUES ('PC Gamer Turbo');
INSERT INTO tb_product (name) VALUES ('PC Gamer Hot');
INSERT INTO tb_product (name) VALUES ('PC Gamer Ez');
INSERT INTO tb_product (name) VALUES ('PC Gamer Tr');
INSERT INTO tb_product (name) VALUES ('PC Gamer Tx');
INSERT INTO tb_product (name) VALUES ('PC Gamer Er');
INSERT INTO tb_product (name) VALUES ('PC Gamer Min');
INSERT INTO tb_product (name) VALUES ('PC Gamer Boo');
INSERT INTO tb_product (name) VALUES ('PC Gamer Foo');

INSERT INTO tb_product_category (product_id, category_id) VALUES (1, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (3, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (4, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (5, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (6, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (7, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (8, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (9, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (10, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (11, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (12, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (13, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (14, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (15, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (16, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (17, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (18, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (19, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (20, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (21, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (22, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (23, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (24, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (25, 3);
